version: '3.3'

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=codejavadb
      - MYSQL_USER=
      - MYSQL_ROOT_PASSWORD=921004_g
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=921004_g
      - PMA_HOST=mysql
    ports:
      - 9090:90
